Update: Workflow to be skipped if secrets env are not available
Signed-off-by: rafaeljohn9 <rafaeljohb@gmail.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -19,17 +19,25 @@ jobs:
         with:
           python-version: '3.12'
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r ask_web_youtube/requirements.txt
-          pip install pytest
 
       - name: Set environment variables from secrets
         run: |
           echo "YOUTUBE_DATA_API_KEY=${{ secrets.YOUTUBE_DATA_API_KEY }}" >> $GITHUB_ENV
           echo "SERPER_API_KEY=${{ secrets.SERPER_API_KEY }}" >> $GITHUB_ENV
           echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV
+
+      - name: Fail if any secrets are missing
+        run: |
+          if [ -z "${{ secrets.YOUTUBE_DATA_API_KEY }}" ] || [ -z "${{ secrets.SERPER_API_KEY }}" ] || [ -z "${{ secrets.GROQ_API_KEY }}" ]; then
+            echo "One or more required secrets are missing."
+            exit 1
+          fi
+          
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r ask_web_youtube/requirements.txt
+          pip install pytest
 
       - name: Run tests
         working-directory: ask_web_youtube
